### PR TITLE
Upgraded to CE3

### PR DESCRIPTION
**Pull request by domaspoliakas**
Hello 👋 

Had to switch IO for SyncIO in tests to be able to run in JS, but otherwise no changes. Took a while because I decided to see if I could switch to munit, but the combination of CE and scalacheck was too much for my limited munit knowledge.

### CODE REVIEW

**Review by rossabaker — APPROVED** [review]
Looks good to me, but may need another wave after https://github.com/typelevel/cats-effect/pull/1477

**Comment by yanns** [comment]
What is the status of this?
It's blocking for the migration of http4s to cats-effect 3.

**Comment by RaasAhsan** [comment]
@yanns There is still some ongoing debate over `Unique` but it's likely it's not going to be in the next milestone release. Can we move forward without it?

**Comment by yanns** [comment]
@RaasAhsan One work-around I see to unblock the situation is to copy and adapt the classes into http4s. But this is quite ugly.

**Comment by RaasAhsan** [comment]
Is another option to have a private Unique be duplicated into vault? None
of these are particularly compelling but any temporary solution to unblock
http4s would be significant

**Comment by domaspoliakas** [comment]
@yanns https://github.com/http4s/http4s/pull/4040 got merged now, so http4s can proceed with the migration until this is merged.

**Pull request merged**
